apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ballroom-competition-web-ingress
  namespace: web
spec:
  ingressClassName: traefik
  tls:
    - secretName: petfoodfinder-app-tls
      hosts:
        - petfoodfinder.app
        - www.petfoodfinder.app
  rules:
    - host: petfoodfinder.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ballroom-competition-web
                port:
                  number: 80
    - host: www.petfoodfinder.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ballroom-competition-web
                port:
                  number: 80
