apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: zot-registry-credentials
  namespace: web
spec:
  itemPath: "vaults/Kubernetes/items/zot-docker-config"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: ballroom-competition-web-firebase
  namespace: web
spec:
  itemPath: "vaults/Kubernetes/items/ballroom-competition-web-firebase"
