apiVersion: v1
kind: Service
metadata:
  name: ballroom-competition-web
  namespace: web
spec:
  selector:
    app: ballroom-competition-web
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
