apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onepassword-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://1password.github.io/onepassword-operator
    chart: onepassword-connect-operator
    targetRevision: 1.8.1
    helm:
      values: |
        operator:
          create: true
          token:
            name: "onepassword-token"
            key: "token"
          connectHost: "http://onepassword-connect:8080"
          watchNamespace: []
        connect:
          create: true
          dataVolume:
            type: emptyDir
            values: {}
          credentials:
            name: "op-credentials"
            key: "1password-credentials.json"
  destination:
    server: https://kubernetes.default.svc
    namespace: onepassword
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
