apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vigilo-ingress
  namespace: web
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - vigilo.zachsexton.com
    secretName: zachsexton-wildcard-tls
  - hosts:
    - vigilo.dev
    secretName: vigilo-dev-tls
  rules:
  - host: vigilo.zachsexton.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vigilo
            port:
              number: 80
  - host: vigilo.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vigilo
            port:
              number: 80
