apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: zot-auth
  namespace: web
spec:
  itemPath: "vaults/Kubernetes/items/zot-htpasswd"
  # Map the 'password' field from 1Password to 'htpasswd' key in the secret
  secretMapping:
    - secretKey: htpasswd
      itemField: password
