apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: ballroom-syllabi-firebase
  namespace: web
spec:
  itemPath: "vaults/Kubernetes/items/ballroom-syllabi-firebase"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: ballroom-syllabi-firebase-sa
  namespace: web
spec:
  itemPath: "vaults/Kubernetes/items/ballroom-syllabi-firebase-sa"
