apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: petfoodfinder-app-cert
  namespace: web
spec:
  secretName: petfoodfinder-app-tls
  issuerRef:
    name: cloudflare-dns
    kind: ClusterIssuer
  dnsNames:
    - petfoodfinder.app
    - www.petfoodfinder.app
