apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vigilo-dev-cert
  namespace: web
spec:
  secretName: vigilo-dev-tls
  issuerRef:
    name: cloudflare-dns
    kind: ClusterIssuer
  dnsNames:
    - vigilo.dev
    - "*.vigilo.dev"
