apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zachsexton-wildcard-cert
  namespace: web
spec:
  secretName: zachsexton-wildcard-tls
  issuerRef:
    name: cloudflare-dns
    kind: ClusterIssuer
  dnsNames:
    - zachsexton.com
    - "*.zachsexton.com"
