apiVersion: v1
kind: Service
metadata:
  name: ballroom-db-nodeport
  namespace: web
spec:
  type: NodePort
  selector:
    postgres-operator.crunchydata.com/cluster: ballroom-db
    postgres-operator.crunchydata.com/role: master
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30432
