apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: external-ips
  namespace: metallb-system
spec:
  addresses:
  - 178.156.205.252-178.156.205.252

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: advertise-external-ips
  namespace: metallb-system
spec:
  ipAddressPools:
  - external-ips
